---
permalink: iscsi-config-esxi/concept_deciding_whether_to_use_this_guide_iscsi_esx.html
sidebar: sidebar
keywords: 
summary: 'This guide describes how to quickly set up the iSCSI service on a storage virtual machine \(SVM\), provision a LUN, and make the LUN available using an iSCSI initiator on an ESX host computer.'
---
= Deciding whether to use the iSCSI Configuration for ESX Express Guide
:icons: font
:imagesdir: ../media/

[.lead]
This guide describes how to quickly set up the iSCSI service on a storage virtual machine (SVM), provision a LUN, and make the LUN available using an iSCSI initiator on an ESX host computer.

This guide is based on the following assumptions:

* You want to use best practices, not explore every available option.
* You do not want to read a lot of conceptual background.
* You want to use System Manager, not the ONTAP command-line interface or an automated scripting tool.
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help/GUID-DF04A607-30B0-4B98-99C8-CB065C64E670.html[ONTAP 9 Cluster Management Using OnCommand System Manager]

* You want to use the _legacy_ OnCommand System Manager UI for ONTAP 9.7 and earlier releases, not the ONTAP System Manager UI for ONTAP 9.7 and later.
+
https://docs.netapp.com/us-en/ontap/[ONTAP System Manager documentation]

* You are using the native ESX iSCSI software initiator on ESXi 5.x.
* You are not using CHAP authentication for iSCSI.
* You are using a supported version of Virtual Storage Console for VMware vSphere to configure storage settings for your ESX host.
* Your network uses IPv4 addressing.
* You want to assign addresses to logical interfaces using any of the following methods:
 ** Automatically from a subnet you define
 ** Manually, using an address selected from an existing subnet
 ** Manually, using an address that will be added to an existing subnet
* You have at least two high-speed Ethernet ports (1 GbE minimum, 10 GbE recommended) available on each node in the cluster.
+
Onboard UTA2 (also called "`CNA`") ports are configurable. You configure those ports in the ONTAP CLI; that process is not covered in this guide.
+
You should see the _ONTAP 9 Network Management Guide_ for using the CLI to configure Ethernet port flow control.
+
https://docs.netapp.com/us-en/ontap/networking/index.html[ONTAP 9 Network Management Guide]

* You are not configuring iSCSI SAN boot.
* You are providing storage to VMs through the ESX hypervisor and not running an iSCSI initiator within the VM.

If these assumptions are not correct for your situation, you should see the following resources:

* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanag/home.html[ONTAP 9 SAN Administration Guide]
* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanconf/home.html[ONTAP 9 SAN Configuration Guide]
* https://docs.netapp.com/vapp-96/topic/com.netapp.doc.vsc-iag/home.html[Appliance administration]
* _VMware vSphere Storage_ for your version of ESX 5 (available from http://www.vmware.com[VMware])
* http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61550[NetApp Documentation: OnCommand Workflow Automation (current releases)]
+
OnCommand Workflow Automation enables you to run prepackaged workflows that automate management tasks such as the workflows described in Express Guides.
