---
permalink: iscsi-config-esxi/task_configuring_your_network_for_best_performance.html
sidebar: sidebar
keywords: ethernet, network, performance, iscsi, configuration, value, configure, configure your network for best performance
summary: "Ethernet networks vary greatly in performance. You can maximize the performance of the network used for iSCSI by selecting specific configuration values."
---
= Configure your network for best performance
:icons: font
:imagesdir: ../media/

[.lead]
Ethernet networks vary greatly in performance. You can maximize the performance of the network used for iSCSI by selecting specific configuration values.

.Steps

. Connect the host and storage ports to the same network.
+
It is best to connect to the same switches. Routing should never be used.

. Select the highest speed ports available, and dedicate them to iSCSI.
+
10 GbE ports are best. 1 GbE ports are the minimum.

. Disable Ethernet flow control for all ports.
+
You should see link:https://docs.netapp.com/us-en/ontap/networking/index.html[ONTAP 9 Network Management] for using the CLI to configure Ethernet port flow control.

. Enable jumbo frames (typically MTU of 9000).
+
All devices in the data path, including initiators, targets, and switches, must support jumbo frames. Otherwise, enabling jumbo frames actually reduces network performance substantially.
