---
permalink: online-help-96-97/concept_what_nvme_subsystem_is.html
sidebar: sidebar
keywords: 
summary: 'An NVMe subsystem includes one or more controllers, one or more namespaces, one or more non-volatile memory \(NVM\) subsystem ports \(FC-NVMe or RDMA transport ports\), an NVM storage medium, and an interface between the controllers and the NVM storage medium. For controller mapping and management, an NVM subsystem maps to a vserver in ONTAP.'
---
= What an NVMe subsystem is
:icons: font
:imagesdir: ../media/

[.lead]
An NVMe subsystem includes one or more controllers, one or more namespaces, one or more non-volatile memory (NVM) subsystem ports (FC-NVMe or RDMA transport ports), an NVM storage medium, and an interface between the controllers and the NVM storage medium. For controller mapping and management, an NVM subsystem maps to a vserver in ONTAP.

An NVMe subsystem can be created using System Manager. You can associate the NVMe subsystem with different hosts and namespaces within the vserver. Also, each vserver can support more than one NVMe subsystem. However, you cannot configure a NVMe subsystem to be used on multiple vservers.

An NVMe over Fabric (NVMeoF) subsystem is a separate kernel object that resides in the FreeBSD kernel. The NVMeoF subsystem interfaces with the following components:

* SAN components, such as BCOMKA, FCT, and VDOM
* WAFL
* RAS components, such as CM, ASUP, and EMS

All interfaces with NVMeoF subsystems adhere to the current definitions and patterns found in ONTAP.
