---
permalink: online-help-96-97/concept_types_svms.html
sidebar: sidebar
keywords: 
summary: 'A cluster consists of four types of SVMs, which help in managing the cluster and its resources and data access to the clients and applications.'
---
= Types of SVMs
:icons: font
:imagesdir: ../media/

[.lead]
A cluster consists of four types of SVMs, which help in managing the cluster and its resources and data access to the clients and applications.

A cluster contains the following types of SVMs:

* Admin SVM
+
The cluster setup process automatically creates the admin SVM for the cluster. The admin SVM represents the cluster.

* Node SVM
+
A node SVM is created when the node joins the cluster, and the node SVM represents the individual nodes of the cluster.

* System SVM (advanced)
+
A system SVM is automatically created for cluster-level communications in an IPspace.

* Data SVM
+
A data SVM represents the data serving SVMs. After the cluster setup, a cluster administrator must create data SVMs and add volumes to these SVMs to facilitate data access from the cluster.
+
A cluster must have at least one data SVM to serve data to its clients.

[NOTE]
====
Unless otherwise specified, the term SVM refers to a data (data-serving) SVM.In the CLI, SVMs are displayed as Vservers.

====
