---
permalink: online-help-96-97/concept_license_types_entitlement_risk.html
sidebar: sidebar
keywords: license, types, entitlement, risk, cluster, online, help
summary: "Understanding the various license types and the associated entitlement risk helps you manage the risk that is associated with the licenses in a cluster."
---
= License types and entitlement risk
:icons: font
:imagesdir: ../media/

[.lead]
Understanding the various license types and the associated entitlement risk helps you manage the risk that is associated with the licenses in a cluster.

== License types

A package can have one or more of the following types of licenses installed in the cluster:

* Node-locked license or standard license
+
A node-locked license is issued for a node with a specific system serial number (also known as a _controller serial number_). This license is valid only for the node that has the matching serial number.
+
Installing a node-locked license entitles a node to the licensed functionality. For the cluster to use the licensed functionality, at least one node must be licensed for the functionality. It might be out of compliance to use the licensed functionality on a node that does not have an entitlement for the functionality.
+
ONTAP 8.2 and later releases treat a license that was installed prior to Data ONTAP 8.2 as a standard license. Therefore, in ONTAP 8.2 and later releases, all of the nodes in the cluster automatically have the standard license for the package that the previously licensed functionality is part of.

* Master or site license
+
A master or site license is not tied to a specific system serial number. When you install a site license, all of the nodes in the cluster are entitled to the licensed functionality.
+
If your cluster has a master license and you remove a node from the cluster, the node does not carry the site license with it, and the node is no longer entitled to the licensed functionality. If you add a node to a cluster that has a master license, the node is automatically entitled to the functionality that is granted by the site license.

* Demo or temporary license
+
A demo or temporary license expires after a certain period of time. This license enables you to try certain software functionality without purchasing an entitlement. A temporary license is a cluster-wide license, and is not tied to a specific serial number of a node.
+
If your cluster has a temporary license for a package and you remove a node from the cluster, the node does not carry the evaluation license with it.

* Capacity license (ONTAP Select and FabricPool only)
+
An ONTAP Select instance is licensed according to the amount of data that the user wants to manage. For example, the user might buy a 10 TB capacity license to enable ONTAP Select to manage up to 10 TB of data. If more storage capacity is attached to the system than ONTAP Select is licensed to manage, ONTAP Select will not operate. By default, the maximum storage capacity that can be attached to an ONTAP Select instance is 2 TB until a capacity license (for example, a 5 TB capacity license, a 10 TB capacity license, and so on) is purchased and installed.
+
Starting with ONTAP 9.2, FabricPool-enabled aggregates require a capacity license to be used with a third-party storage tier (for example, AWS). The FabricPool capacity license defines the amount of data that can be stored in the cloud tier storage.

== Entitlement risk

An entitlement risk arises because of the non-uniform installation of a node-locked license. If the node-locked license is installed on all the nodes, there is no entitlement risk.

The entitlement risk level can be high risk, medium risk, no risk, or unknown risk depending on certain conditions:

* High risk
 ** If there is usage on a particular node, but the node-locked license is not installed on that node
 ** If the demo license that was installed on the cluster expires, and there is usage on any node

+
[NOTE]
====
If a site license is installed on a cluster, the entitlement risk is never high.
====
* Medium risk
+
If a site license is not installed, and the node-locked license is non-uniformly installed on the nodes in a cluster

* No risk
+
There is no entitlement risk if a node-locked license is installed on all of the nodes, or a site license is installed on the cluster, irrespective of usage.

* Unknown
+
The risk is unknown if the API is sometimes unable to retrieve the data related to entitlement risk that is associated with a cluster or the nodes in the cluster.
