---
permalink: online-help-96-97/concept_requirements_best_practices_for_using_ssd_storage_pools.html
sidebar: sidebar
keywords: requirements, best, practices, ssd, storage, flash, pool, aggregate, online, help
summary: "Some technologies cannot be combined with Flash Pool aggregates that use SSD storage pools."
---
= Requirements and best practices for using SSD storage pools
:icons: font
:imagesdir: ../media/

[.lead]
Some technologies cannot be combined with Flash Pool aggregates that use SSD storage pools.

You cannot use the following technologies with Flash Pool aggregates that use SSD storage pools for their cache storage:

* MetroCluster
* SyncMirror functionality
+
Mirrored aggregates can coexist with Flash Pool aggregates that use storage pools; however, Flash Pool aggregates cannot be mirrored.

* Physical SSDs
+
Flash Pool aggregates can use SSD storage pools or physical SSDs, but not both.

SSD storage pools must conform to the following rules:

* SSD storage pools can contain only SSDs; HDDs cannot be added to an SSD storage pool.
* All of the SSDs in an SSD storage pool must be owned by the same high-availability (HA) pair.
* You cannot use SSDs that have been partitioned for root-data partitioning in a storage pool.

If you provide storage from a single storage pool to two caches with different RAID types, and you expand the size of the storage pool beyond the maximum RAID group size for RAID4, the extra partitions in the RAID4 allocation units go unused. Therefore, it is a best practice to keep your cache RAID types homogenous for a storage pool.

You cannot change the RAID type of cache RAID groups that are allocated from a storage pool. You set the RAID type for the cache before adding the first allocation units, and you cannot change the RAID type later.

When you create a storage pool or add SSDs to an existing storage pool, you must use the same size SSDs. If a failure occurs and no spare SSD of the correct size exists, ONTAP can use a larger SSD to replace the failed SSD. However, the larger SSD is right-sized to match the size of the other SSDs in the storage pool, resulting in lost SSD capacity.

You can use only one spare SSD for a storage pool. If the storage pool provides allocation units to the Flash Pool aggregates that are owned by both nodes in the HA pair, then the spare SSD can be owned by either node. However, if the storage pool provides allocation units only to the Flash Pool aggregates that are owned by one of the nodes in the HA pair, then the SSD spare must be owned by that same node.
