---
permalink: online-help-96-97/concept_jobs_conceptual.html
sidebar: sidebar
keywords: job, asynchronous, volume, operation, copy, move, mirror, data, queue, cluster, administrator, online, help
summary: "Jobs are asynchronous task and typically long-running volume operations, such as copying, moving, or mirroring data. Jobs are placed in a job queue and are run when resources are available. The cluster administrator can perform all the tasks related to job management."
---
= Jobs
:icons: font
:imagesdir: ../media/

[.lead]
_Jobs_ are asynchronous task and typically long-running volume operations, such as copying, moving, or mirroring data. Jobs are placed in a job queue and are run when resources are available. The cluster administrator can perform all the tasks related to job management.

A job can be one of the following categories:

* A _server-affiliated_ job is placed in queue by the management framework to be run in a specific node.
* A _cluster-affiliated_ job is placed in queue by the management framework to be run in any node in the cluster.
* A _private_ job is specific to a node and does not use the replicated database (RDB) or any other cluster mechanism.
+
You require the advanced privilege level or higher to run the commands to manage private jobs.

You can manage jobs in the following ways:

* Displaying job information, including the following:
 ** Jobs on a per-node basis
 ** Cluster-affiliated jobs
 ** Completed jobs
 ** Job history
* Monitoring a job's progress
* Displaying information about the initialization state for job managers.

You can determine the outcome of a completed job by checking the event log.
