---
permalink: online-help-96-97/concept_minimum_number_hot_spares_you_should_have.html
sidebar: sidebar
keywords: 
summary: 'Having insufficient spares increases the risk of a disk failure with no available spare, resulting in a degraded RAID group. A spare disk is also required to provide important information \(a core file\) to technical support in case of a controller disruption.'
---
= Minimum number of hot spares required for disks
:icons: font
:imagesdir: ../media/

[.lead]
Having insufficient spares increases the risk of a disk failure with no available spare, resulting in a degraded RAID group. A spare disk is also required to provide important information (a _core file_) to technical support in case of a controller disruption.

MSATA disks, or disks in a multi-disk carrier, should have four hot spares during steady state operation, and you should never allow the number of MSATA hot spares to dip below two.

For RAID groups composed of SSDs, you should have at least one spare disk.

For all other ONTAP disk types, you should have at least one matching or appropriate hot spare available for each kind of disk installed in your storage system. However, having two available hot spares for all disks provides the best protection against disk failure. Having at least two available hot spares provides the following benefits:

* When you have two or more hot spares for a data disk, ONTAP can put that disk into the maintenance center if required.
+
ONTAP uses the maintenance center to test suspect disks and to take offline any disk that shows problems.

* Having two hot spares means that when a disk fails, you still have a spare disk available if another disk fails before you replace the first failed disk.

A single spare disk can serve as a hot spare for multiple RAID groups. However, if any disk in those RAID groups fails, then no spare disk is available for any future disk failures or for a core file until the spare disk is replaced. Therefore, it is a best practice to have more than one spare.
