---
permalink: online-help-96-97/reference_nvme_namespaces_window.html
sidebar: sidebar
keywords: nvme, namespace, command, button, subsystems, protocol, online, help
summary: "You can use the NVMe namepaces window to set up and manage your namespaces and associated subsytems for the NVMe protocol. You can search for an existing namespace using the namespace path."
---
= NVMe namespaces window
:icons: font
:imagesdir: ../media/

[.lead]
You can use the NVMe namepaces window to set up and manage your namespaces and associated subsytems for the NVMe protocol. You can search for an existing namespace using the namespace path.

== Command Buttons

* *Create*
+
Opens the NVMe namespace create dialog box, which allows you to set up a new namespace and map it to an NVMe subsystem.

* *Edit*
+
Enables you to edit the namespace mapping.

* *Delete*
+
Deletes the selected namespace.

* *More Actions*
+
Allows you to create a clone of the selected namespace, which can be associated with an existing subsystem, or you can choose not to map it to a subsystem.

* *Refresh*
+
Updates the information in the window.

== NVMe List

* *Status*
+
Displays if the namespace is online or offline.

* *Namespace Path*
+
The path to the new namespace in the `/vol/volume'/file` format. The namespace path is a clickable link. Clicking the link takes you to the namespace detailspage.

* *NVMe Subsystem*
+
The name of the subsystem attached to a namespace. If no subsystems are attached, the value of this column is shown as `None`. You can see the list of unmapped namespaces by filtering this column for NVMe subsystem contains `None`.

* *SVMs*
+
The SVM name on which the namespace is created. The SVM name is a clickable link. Clicking the link takes you to the existing SVM dashboard page.
+
Starting with ONTAP 9.5, at least one NVMe LIF must be configured for each node of a HA pair associated with the SVM. You can create a maximum of two NVMe LIFs for each node in the pair.

* *Namespace ID*
+
A unique identifier used by the controller to provide access to a namespace. This is not a user input; it is generated by the system when the new namespace is created.

* *Total Space*
+
Displays the total size of the namespace.

* *Used Space*
+
Displays the amount of used space in the namespace.

* *%Used*
+
Displays the amount of space (in percentage) that is used in the namespace. The value for this field is calculated using total and used space.

== Details Area

You can select a namespace to view information about the selected namespace. From this area, you can also edit, delete or clone the namespace.

* ***Overview* tab**
+
Displays general information about the selected namespace, and displays a pictorial representation of the space allocation of the namespace and the performance of the namespace.
+
In the Overview tab, the SVM and volume names are clickable links. Clicking the link takes you to the SVM and volume pages, respectively. The number of hosts can be one or more; by default two host names are shown. If more than two host names are shown, you can click a link to access the additional hosts.
+
The Overview tab also displays a space chart that shows the total and used space details for the namespace and a performance chart that shows details such as latency, IOPS, and throughput.

* *Status*
+
The status of the namespace; the value can be online or offline.

* *Host NQN*
+
The host NVMe Qualified Names (NQNs) uniquely describes the host for the purposes of identification and authentication. This field can accept comma separated NVMe qualification name (NQN) values. The host NQN starts with `nqn` and rest of the validation is the same as the initiator qualification name (IQN).

* *Host OS*
+
The host operating system for the namespace: Hyper-V, Linux, VMware, Windows or Xen.

* *Volume*
+
Displays the volume name on which the namespace is hosted.

* *Read-Only*
+
Displays whether the namespace is read-only or not.

* *Node*
+
The node that owns the namespace.

* *Block Size*
+
The size of the storage block.

* *Restore Inaccessible*
+
If unmapping a subsystem fails and partial data remains, unmapped namespaces cannot be restored.
