---
permalink: online-help-96-97/reference_array_luns_window_stm_topic.html
sidebar: sidebar
keywords: 
summary: 'The Array LUNs window enables you to assign ownership to your array LUNs and to add them to an aggregate.'
---
= Array LUNs window
:icons: font
:imagesdir: ../media/

[.lead]
The Array LUNs window enables you to assign ownership to your array LUNs and to add them to an aggregate.

The Array LUNs link in the left navigation pane is displayed only if there are any spare array LUNs, or if the V_StorageAttach license is installed.

* <<GUID-98901AC2-473A-42AF-A4C0-AE2CCEF87EB1,#GUID-98901AC2-473A-42AF-A4C0-AE2CCEF87EB1>>
* <<GUID-F9609C8D-1BA8-4403-81FC-6848244E0E6C,#GUID-F9609C8D-1BA8-4403-81FC-6848244E0E6C>>
* <<GUID-42C6F1D0-B6DD-4F29-B2C6-F5CFB28FF279,#GUID-42C6F1D0-B6DD-4F29-B2C6-F5CFB28FF279>>

== Command buttons

* *Assign*
+
Enables you to assign or reassign the ownership of array LUNs to a node.

* *Zero Spares*
+
Erases all the data, and formats the spare array LUNs and disks.

* *Refresh*
+
Updates the information in the window.

== Array LUN list

Displays information such as the name, state, and vendor for each array LUN.

* *Name*
+
Specifies the name of the array LUN.

* *State*
+
Specifies the state of the array LUN.

* *Vendor*
+
Specifies the name of the vendor.

* *Used Space*
+
Specifies the space used by the array LUN.

* *Total Size*
+
Specifies the size of the array LUN.

* *Container*
+
Specifies the aggregate to which the array LUN belongs.

* *Node name*
+
Specifies the name of the node to which the array LUN belongs.

* *Home owner*
+
Displays the name of the home node to which the array LUN is assigned.

* *Current owner*
+
Displays the name of the node that currently owns the array LUN.

* *Array name*
+
Specifies the name of the array.

* *Pool*
+
Displays the name of the pool to which the selected array LUN is assigned.

== Details area

The area below the Array LUNs list displays detailed information about the selected array LUN.
