---
permalink: online-help-96-97/reference_how_flash_cache_modules_work.html
sidebar: sidebar
keywords: 
summary: 'Using Flash Cache modules improves the performance of a storage system. The impact of using Flash Cache modules is displayed on the Hardware Cache window.'
---
= How Flash Cache modules work
:icons: font
:imagesdir: ../media/

[.lead]
Using Flash Cache modules improves the performance of a storage system. The impact of using Flash Cache modules is displayed on the Hardware Cache window.

You can configure Flash Cache modules and disks based on the workload requirements of a storage system. By determining the read workload (number of read operations) served by Flash Cache modules and disks, you can analyze the performance of the storage system.

Flash Cache modules do not contain any data during the storage system boot or when control is returned to the storage system after a takeover event. Therefore, disks serve all the data read requests of the storage system.

The Flash Cache module is slowly populated with data when data read requests are served. Because the data read requests served by Flash Cache modules are faster than those served by the disks, the performance of the storage system improves.

Data read requests served by the Flash Cache module replace the data read requests served by the disks, and therefore, the performance improvement in the storage system is directly related to the disk reads that are replaced. To understand the impact of Flash Cache modules on storage system performance, you must view the read workload graph in the Hardware Cache window when the Flash Cache module contains data.
