---
permalink: online-help-96-97/reference_snapshot_policies_window.html
sidebar: sidebar
keywords: snapshot, policies, window, command, buttons, online, help
summary: "You can use the Snapshot Policies window to manage Snapshot policy tasks, such as adding, editing, and deleting Snapshot policies."
---
= Snapshot Policies window
:icons: font
:imagesdir: ../media/

[.lead]
You can use the Snapshot Policies window to manage Snapshot policy tasks, such as adding, editing, and deleting Snapshot policies.

== Command buttons

* *Create*
+
Opens the Create Snapshot Policy dialog box, which enables you to add backup schedules and specify the maximum number of Snapshot copies to be retained in a policy.

* *Edit*
+
Opens the Edit Snapshot Policy dialog box, which enables you to modify the frequency at which Snapshot copies should be created and the maximum number of Snapshot copies to be retained.

* *Delete*
+
Opens the Delete dialog box, which enables you to delete the selected Snapshot policy.

* *View as*
+
Enables you to view the Snapshot policies either as a list or as a tree.

* *Status*
+
Opens the menu, which you can use to either enable or disable the selected Snapshot policy.

* *Refresh*
+
Updates the information in the window.

== Snapshot policy list

* *Policy/Schedule Name*
+
Specifies the name of the Snapshot policy and the schedules in the policy.

* *Storage Virtual Machine*
+
Specifies the name of the storage virtual machine (SVM) to which the Snapshot copies belong.

* *Status*
+
Specifies the status of the Snapshot policy, which can be Enabled or Disabled.

* *Maximum Snapshots to be retained*
+
Specifies the maximum number of Snapshot copies to be retained.

* *SnapMirror Label*
+
Specifies the name of the SnapMirror label attribute of the Snapshot copy generated by the backup schedule.
