---
permalink: online-help-96-97/reference_system_health_window.html
sidebar: sidebar
keywords: 
summary: 'You can use the System Alerts window to learn more about system health alerts. You can also acknowledge, delete, and suppress alerts from the window.'
---
= System Alerts window
:icons: font
:imagesdir: ../media/

[.lead]
You can use the System Alerts window to learn more about system health alerts. You can also acknowledge, delete, and suppress alerts from the window.

== Command buttons

* *Acknowledge*
+
Enables you to acknowledge the selected alert to indicate that the problem is being addressed and identifies the person who clicks the button as the "`Acknowledger.`"

* *Suppress*
+
Enables you to suppress the selected alert to prevent the system from notifying you about the same alert again and identifies you as the "`Suppressor.`"

* *Delete*
+
Deletes the selected alert.

* *Refresh*
+
Updates the information in the window.

== Alerts list

* *SubSystem (No. of Alerts)*
+
Displays the name of the subsystem, such as the SAS connection, switch health, CIFS NDO, or MetroCluster, for which the alert is generated.

* *Alert ID*
+
Displays the alert ID.

* *Node*
+
Displays the name of the node for which the alert is generated.

* *Severity*
+
Displays the severity of the alert as Unknown, Other, Information, Degraded, Minor, Major, Critical, or Fatal.

* *Resource*
+
Displays the resource that generated the alert, such as a specific shelf or disk.

* *Time*
+
Displays the time when the alert was generated.

== Details area

The details area displays detailed information about the alert, such as the time when the alert was generated and whether the alert has been acknowledged. The area also includes information about the probable cause and possible effect of the condition generated by the alert, and the recommended actions to correct the problem reported by the alert.

*Related information*

xref:task_acknowledging_system_health_alerts.adoc[Acknowledging system health alerts]

xref:task_suppressing_system_health_alerts.adoc[Suppressing system health alerts]

xref:task_deleting_system_health_alerts.adoc[Deleting system health alerts]
