---
permalink: online-help-96-97/task_editing_qos_policy_groups.html
sidebar: sidebar
keywords: 
summary: 'You can use the Edit Policy Group dialog box in System Manager to modify the name and maximum throughput of an existing storage Quality of Service \(QoS\) policy group.'
---
= Editing QoS policy groups
:icons: font
:imagesdir: ../media/

[.lead]
You can use the Edit Policy Group dialog box in System Manager to modify the name and maximum throughput of an existing storage Quality of Service (QoS) policy group.

== About this task

* In System Manager 9.5, you can set the minimum throughput limit only on a performance-based All Flash Optimized personality. In System Manager 9.6, you can also set the minimum throughput limit for ONTAP Select Premium systems.
* You cannot set the minimum throughput limit for volumes on a FabricPool-enabled aggregate.

== Steps

. Click *Storage* > *SVMs*.
. Select the SVM, and then click *SVM Settings*.
. In the *Policies* pane, click *QoS Policy Groups*.
. Select the QoS policy group that you want to edit, and then click *Edit*.
 ** The minimum throughput limit and the maximum throughput limit must be of the same unit type.
 ** If you do not specify the minimum throughput limit, you can set the maximum throughput limit in IOPS and B/s, KB/s, MB/s, and so on.
 ** If you do not specify the maximum throughput limit, the value is set to unlimited, and the unit that you specify does not affect the maximum throughput.
. In the *Edit Policy Group* dialog box, edit the QoS policy group details, and then click *Save*.
