---
permalink: online-help-96-97/task_creating_cifs_share.html
sidebar: sidebar
keywords: 
summary: 'You can use System Manager to create a CIFS share that enables you to specify the folder, qtree, or volume that CIFS users can access.'
---
= Creating a CIFS share
:icons: font
:imagesdir: ../media/

[.lead]
You can use System Manager to create a CIFS share that enables you to specify the folder, qtree, or volume that CIFS users can access.

== Before you begin

You must have installed the CIFS license before you set up and start CIFS.

== Steps

. Click *Storage* > *Shares*.
. From the drop-down menu in the *SVM* field, select the SVM on which you want to create a CIFS share.
. Click *Create Share*.
. In the *Create Share* window, click *Browse*, and then select the folder, qtree, or volume that should be shared.
. Specify a name for the new CIFS share.
. Select the *Enable continuous availability for Hyper-V and SQL* check box to permit clients that support SMB 3.0 and later to open files persistently during nondisruptive operations.
+
Files that are opened by using this option are protected from disruptive events such as failover, giveback, and LIF migration.
+
Starting with System Manager 9.6, continuous availability is supported for FlexGroup volumes.

. Select the *Encrypt data while accessing this share* check box to enable SMB 3.0 encryption.
. Provide a description or comment for the share, and then click *Create*.

== Results

The CIFS share is created with the access permissions set to "`Full Control for Everyone`" in the group.

*Related information*

xref:task_setting_up_cifs.adoc[Setting up CIFS]

xref:reference_shares_window.adoc[Shares window]
