---
permalink: online-help-96-97/task_creating_a_node_management_logical_interface.html
sidebar: sidebar
keywords: 
summary: 'You can use System Manager to create a dedicated node management logical interface \(LIF\) for managing a particular node in a cluster. You can use this LIF to manage the system maintenance activities of the node.'
---
= Creating a node management logical interface
:icons: font
:imagesdir: ../media/

[.lead]
You can use System Manager to create a dedicated node management logical interface (LIF) for managing a particular node in a cluster. You can use this LIF to manage the system maintenance activities of the node.

. Click *Configuration* > *Cluster* > *Configuration Updates*.
. In the *Nodes* tab, select the node for which you want to create a node management LIF, and then click *Create Node-Management LIF*.
. In the *Create Node-Management LIF* dialog box, specify a name for the node management LIF.
. Assign the IP address to the node management LIF:
+
|===
| If you want to...| Then...
a|
Specify the IP address by using a subnet
a|

 .. Select *Using a subnet*.
 .. In the Add Details dialog box, select the subnet from which the IP address should be assigned.
+
For an intercluster LIF, only the subnets that are associated with the selected IPspace are displayed.

 .. If you want to assign a specific IP address to the LIF, select *Use a specific IP address*, and then type the IP address.
+
The IP address that you specify is added to the subnet if the IP address is not already present in the subnet range.

 .. Click *OK*.

a|
Specify the IP address manually without using a subnet
a|

 .. Select *Without a subnet*.
 .. In the Add Details dialog box, perform the following steps:
  ... Specify the IP address and the network mask or prefix.
  ... Optional: Specify the gateway.
  ... If you do not want to use the default value for the Destination field, specify a new destination value.
+
If you do not specify a value, the Destination field is populated with the default value based on the family of the IP address.

+
If a route does not exist, a new route is automatically created based on the gateway and destination.
 .. Click *OK*.

+
|===

. Select the required ports from the *Ports details* area.
. Click *Create*.

If you want to delete an existing node management LIF, you must use the command-line interface (CLI).
