---
permalink: online-help-96-97/task_deleting_nvme_subsystem.html
sidebar: sidebar
keywords: delete, nvme, subsystem, online, help, system, manager, cluster
summary: "You can use System Manager to delete an NVMe subsystem from a cluster."
---
= Deleting an NVMe subsystem
:icons: font
:imagesdir: ../media/

[.lead]
You can use System Manager to delete an NVMe subsystem from a cluster.

.About this task

The following actions occur when you delete an NVMe subsystem:

* If the NVMe subsystem has configured hosts, then mapped hosts will be removed.
* If the NVMe subsystem has mapped namespaces, then they will be unmapped.

.Steps

. Find the NVMe subsystem you want to delete on the *NVMe Subsystem* window.
. Check the box to the left of the name of the subsystem you want to delete.
. Click *Delete*.
+
A Warning message is displayed.

. Click the *Delete the NVMe Subsystem* check box to confirm the deletion, then click *Yes*.
+
The NVMe subsystem is deleted from the cluster, and the NVMe Subsystems window is displayed.

*Related information*

xref:reference_nvme_subsystems_window.adoc[NVMe Subsystems window]
