---
permalink: online-help-96-97/task_mounting_volumes.html
sidebar: sidebar
keywords: 
summary: 'You can use System Manager to mount volumes to a junction in the storage virtual machine \(SVM\) namespace.'
---
= Mounting volumes
:icons: font
:imagesdir: ../media/

[.lead]
You can use System Manager to mount volumes to a junction in the storage virtual machine (SVM) namespace.

== About this task

* If you mount a volume to a junction path with a language setting that is different from that of the immediate parent volume in the path, NFSv3 clients cannot access some of the files because some characters might not be decoded correctly.
+
This issue does not occur if the immediate parent directory is the root volume.

* You can mount a SnapLock volume only under the root of the SVM.
* You cannot mount a regular volume under a SnapLock volume.

== Steps

. Click *Storage* > *Junction Path*.
. From the drop-down menu in the *SVM* field, select the SVM on which you want to mount a volume.
. Click *Mount*, and then select the volume that is to be mounted.
. If you want to change the default junction name, specify a new name.
. Click *Browse*, and then select the junction path to which you want to mount the volume.
. Click *OK*, and then click *Mount*.
. Verify the new junction path in the *Details* tab.
