---
permalink: online-help-96-97/task_provisioning_storage_by_creating_aggregate_based_on_storage_recommendations.html
sidebar: sidebar
keywords: provision, storage, create, aggregate, recommendation, system, manager, online, help
summary: "You can use System Manager to create an aggregate based on storage recommendations. System Manager analyzes the configuration of your storage system and provides storage recommendations such as the number of aggregates that will be created, the available nodes, and the available spare disks."
---
= Provisioning storage by creating an aggregate based on storage recommendations
:icons: font
:imagesdir: ../media/

[.lead]
You can use System Manager to create an aggregate based on storage recommendations. System Manager analyzes the configuration of your storage system and provides storage recommendations such as the number of aggregates that will be created, the available nodes, and the available spare disks.

== About this task

* You cannot create an aggregate based on storage recommendations in Cloud Volumes ONTAP, ONTAP Select, and MetroCluster configurations.
* Errors, if any, are displayed on the screen.
+
You can fix these errors and then create an aggregate based on the storage recommendations, or you can create an aggregate manually.

== Steps

. Create an aggregate by using one of the following methods:
 ** Click *Applications & Tiers* > *Storage Tiers* > *Add Aggregate*.
 ** Click *Storage* > *Aggregate & Disks* > *Aggregates* > *Create*.
. Review the storage recommendations, and then click *Submit*.
+
The Information dialog box displays the status of the aggregates.

. Click *Run in Background* to navigate to the *Aggregates* window.
. Click *Refresh* to view the aggregates that are created.
