---
permalink: online-help-96-97/task_editing_local_windows_group_properties.html
sidebar: sidebar
keywords: online, help, edit, local, windows, group, properties, active, directory
summary: "You can manage local group memberships by adding and removing a local user, an Active Directory user, or an Active Directory group by using System Manager. You can modify the privileges that are assigned to a group and the description of a group to easily identify the group."
---
= Editing local Windows group properties
:icons: font
:imagesdir: ../media/

[.lead]
You can manage local group memberships by adding and removing a local user,an Active Directory user, or an Active Directory group by using System Manager. You can modify the privileges that are assigned to a group and the description of a group to easily identify the group.

.About this task

You must keep the following in mind when adding members to or removing members from a local Windows group:

* You cannot add users to or remove users from the special _Everyone_ group.
* You cannot add a local Windows group to another local Windows group.

.Steps

. Click *Storage* > *SVMs*.
. Select the SVM, and then click *SVM Settings*.
. In the *Host Users and Groups* pane, click *Windows*.
. In the *Groups* tab, click *Edit*.
. Specify a name for the group and a description to identify the new group.
. Assign a set of privileges to the group.
+
You can select the privileges from the predefined set of supported privileges.

. Click *Add* to add users to the group.
. In the *Add Members* window, perform one of the following actions:
 ** Specify the Active Directory user or Active Directory group to be added to a particular local group.
 ** Select the users from the list of available local users in the storage virtual machine (SVM).
. Click *Edit*.

.Results

The local Windows group settings are modified, and the changes are displayed in the *Groups* tab.

*Related information*

xref:reference_windows_window.adoc[Windows window]
