---
permalink: online-help-96-97/task_deleting_mirror_and_vault_relationships.html
sidebar: sidebar
keywords: 
summary: 'You can use System Manager to end a mirror and vault relationship between a source and destination volume, and release the Snapshot copies from the source volume.'
---
= Deleting mirror and vault relationships
:icons: font
:imagesdir: ../media/

[.lead]
You can use System Manager to end a mirror and vault relationship between a source and destination volume, and release the Snapshot copies from the source volume.

* It is a best practice to break the mirror and vault relationship before deleting the relationship.
* To re-create the relationship, you must run the resynchronization operation from the source volume by using the command-line interface (CLI).

. Click *Protection* > *Volume Relationships*.
. Select the mirror and vault relationship that you want to delete and click *Delete*.
. Select the confirmation check box, and then click *Delete*.
+
You can also select the release base Snapshot copies check box to delete the base Snapshot copies used by the mirror and vault relationship on the source volume.
+
If the relationship is not released, then you must use the CLI to run the release operation on the source cluster to delete the base Snapshot copies that were created for the mirror and vault relationship from the source volume.

The relationship is deleted and the base Snapshot copies on the source volume are permanently deleted.
