---
permalink: online-help-96-97/task_adding_user_accounts_to_windows_local_group.html
sidebar: sidebar
keywords: add, user, accounts, windows, local, group, active, directory, online, help
summary: "You can add a local user, an Active Directory user, or an Active Directory group (if you want users to have the privileges that are associated with that group)to a Windows local group by using System Manager."
---
= Add user accounts to a Windows local group
:icons: font
:imagesdir: ../media/

[.lead]
You can add a local user, an Active Directory user, or an Active Directory group(if you want users to have the privileges that are associated with that group)to a Windows local group by using System Manager.

.Before you begin

* The group must exist before you can add a user to the group.
* The user must exist before you can add the user to a group.

.About this task

You must keep the following in mind when adding members to a local Windows group:

* You cannot add users to the special _Everyone_ group.
* You cannot add a local Windows group to another local Windows group.
* You cannot add a user account that contains a space in the user name by using System Manager.
+
You can either rename the user account or add the user account by using the command-line interface (CLI).

.Steps

. Click *Storage* > *SVMs*.
. Select the SVM, and then click *SVM Settings*.
. In the *Host Users and Groups* pane, click *Windows*.
. In the *Groups* tab, select the group to which you want to add a user, and then click *Add Members*.
. In the *Add Members* window, perform one of the following actions:
 ** Specify the Active Directory user or Active Directory group to be added to a particular local group.
 ** Select the users from the list of available local users in the storage virtual machine (SVM).
. Click *OK*.

.Results

The user that you added is listed in the Userstab of the *Groups* tab.

*Related information*

xref:reference_windows_window.adoc[Windows window]
