---
permalink: online-help-96-97/task_migrating_lif.html
sidebar: sidebar
keywords: 
summary: 'You can use System Manager to migrate a data LIF or a cluster management LIF to a different port on the same node or on a different node within the cluster if the source port is faulty or requires maintenance.'
---
= Migrating a LIF
:icons: font
:imagesdir: ../media/

[.lead]
You can use System Manager to migrate a data LIF or a cluster management LIF to a different port on the same node or on a different node within the cluster if the source port is faulty or requires maintenance.

== Before you begin

The destination node and ports must be operational and must be able to access the same network as the source port.

== About this task

* If you are removing the NIC from the node, you must migrate the LIFs that are hosted on the ports belonging to the NIC to other ports in the cluster.
* You cannot migrate iSCSI LIFs or FC LIFs.

== Steps

. Click *Network* > *Network Interfaces*.
. Select the interface that you want to migrate, and then click *Migrate*.
. In the *Migrate Interface* dialog box, select the destination port to which you want to migrate the LIF.
. Select the *Migrate Permanently* check box if you want to set the destination port as the new home port for the LIF.
. Click *Migrate*.
