---
permalink: online-help-96-97/task_assigning_group_memberships_to_a_user_account.html
sidebar: sidebar
keywords: 
summary: 'You can use System Manager to assign group membership to a user account if you want a user to have the privileges that are associated with a particular group.'
---
= Assigning group memberships to a user account
:icons: font
:imagesdir: ../media/

[.lead]
You can use System Manager to assign group membership to a user account if you want a user to have the privileges that are associated with a particular group.

* The group must exist before you can add a user to the group.
* The user must exist before you can add the user to a group.

You cannot add users to the special _Everyone_ group.

. Click *Storage* > *SVMs*.
. Select the SVM, and then click *SVM Settings*.
. In the *Host Users and Groups* pane, click *Windows*.
. In the *Users* tab, select the user account to which you want to assign group memberships, and then click *Add to Group*.
. In the *Add Groups* window, select the groups to which you want to add the user account.
. Click *OK*.

The user account is assigned membership to all of the selected groups, and the user has the privileges that are associated with these groups.

*Related information*

xref:reference_windows_window.adoc[Windows window]
