---
permalink: online-help-96-97/task_mirroring_aggregates.html
sidebar: sidebar
keywords: 
summary: 'You can use System Manager to protect data and to provide increased resiliency by mirroring data in real-time, within a single aggregate. Mirroring aggregates removes single points of failure in connecting to disks and array LUNs.'
---
= Mirroring aggregates
:experimental:
:icons: font
:imagesdir: ../media/

[.lead]
You can use System Manager to protect data and to provide increased resiliency by mirroring data in real-time, within a single aggregate. Mirroring aggregates removes single points of failure in connecting to disks and array LUNs.

== Before you begin

There must be sufficient free disks in the other pool to mirror the aggregate.

== About this task

You cannot mirror a Flash Pool aggregate when the cache source is storage pool.

== Steps

. Choose one of the following methods:
 ** Click *Applications & Tiers* > *Storage Tiers*.
 ** Click *Storage* > *Aggregates & Disks* > *Aggregates*.
. Select the aggregate that you want to mirror, and then click menu:More Actions[Mirror].
+
[NOTE]
====
SyncMirror is not supported on FabricPool-enabled aggregates.
====

. In the *Mirror this aggregate* dialog box, click *Mirror* to initiate the mirroring.
