---
permalink: online-help-96-97/task_changing_default_initiator_authentication_method.html
sidebar: sidebar
keywords: change, default, iscsi, initiator, authentication, method, online, help
summary: "You can use System Manager to change the default iSCSI authentication method, which is the authentication method that is used for any initiator that is not configured with a specific authentication method."
---
= Changing the default iSCSI initiator authentication method
:icons: font
:imagesdir: ../media/

[.lead]
You can use System Manager to change the default iSCSI authentication method, which is the authentication method that is used for any initiator that is not configured with a specific authentication method.

.Steps

. Click *Storage* > *SVMs*.
. Select the SVM, and then click *SVM Settings*.
. In the *Protocols* pane, click *iSCSI*.
. In the *Initiator Security* tab, click *Edit* in the *Default Security* area.
. Change the security type.
+
For CHAP authentication, you must provide the user name and password, and then confirm your password for inbound settings. For outbound settings, this login information is optional.

. Click *OK*.

*Related information*

xref:reference_iscsi_window.adoc[iSCSI window]
