---
permalink: online-help-96-97/task_changing_password_for_windows_local_users.html
sidebar: sidebar
keywords: reset, password, windows, local, user, online, help, system, manager
summary: "You can use System Manager to reset the password of a Windows local user. For example, you might want to reset the password if the current password is compromised or if the user has forgotten the password."
---
= Resetting the password of a Windows local user
:icons: font
:imagesdir: ../media/

[.lead]
You can use System Manager to reset the password of a Windows local user. For example, you might want to reset the password if the current password is compromised or if the user has forgotten the password.

.About this task

The password that you set must meet the following criteria:

* Must be at least six characters in length
* Must not contain the user account name
* Must contain characters from at least three of the following four categories:
 ** English uppercase characters (A through Z)
 ** English lowercase characters (a through z)
 ** Base 10 digits (0 through 9)
 ** Special characters: ~ ! @ # 0 {caret} & * _ - + = ` \ | ( ) [ ] : ; " ' < > , . ? /

.Steps

. Click *Storage* > *SVMs*.
. Select the SVM, and then click *SVM Settings*.
. In the *Host Users and Groups* pane, click *Windows*.
. In the *Users* tab, select the user whose password you want to reset, and then click *Set Password*.
. In the *Reset Password* dialog box, set a new password for the user.
. Confirm the new password, and then click *Reset*.

*Related information*

xref:reference_windows_window.adoc[Windows window]
