---
permalink: online-help-96-97/task_extending_the_expiry_date_of_snapshot_copies.html
sidebar: sidebar
keywords: 
summary: 'You can use System Manager to extend the expiry date of the Snapshot copies in a volume.'
---
= Extending the expiry date of Snapshot copies
:icons: font
:imagesdir: ../media/

[.lead]
You can use System Manager to extend the expiry date of the Snapshot copies in a volume.

The SnapLock license must be installed on your system.

You can extend the expiry date only for Snapshot copies in a data protection (DP) volume that is the destination in a SnapLock for SnapVault relationship.

. Click *Storage* > *Volumes*.
. From the drop-down menu in the *SVM* field, select *All SVMs*.
. Select a volume.
. Click *Show More Details* to view more information about the volume.
. Click the *Snapshot Copies* tab.
+
The list of available Snapshot copies for the selected volume is displayed.

. Select the Snapshot copy that you want to modify, and then click *Extend Expiry Date*.
. In the *Extend Expiry Date* dialog box, specify the expiry date.
+
The values must be in the range of 1 day through 70 years or Infinite.

. Click *OK*.
