---
permalink: online-help-96-97/task_provisioning_storage_by_creating_fabricpool_aggregate_manually.html
sidebar: sidebar
keywords: ssd, provision, storage, fabricpool, aggregate, manually, system, manager, online, help, cloud, tier
summary: "You can use System Manager to create a FabricPool-enabled aggregate to attach a cloud tier to the SSD aggregate."
---
= Provisioning storage by creating a FabricPool-enabled aggregate manually
:icons: font
:imagesdir: ../media/

[.lead]
You can use System Manager to create a FabricPool-enabled aggregate to attach a cloud tier to the SSD aggregate.

.Before you begin

* You must have created a cloud tier and attached it to the cluster in which the SSD aggregate resides.
* An on-premises cloud tier must have been created.
* A dedicated network connection must exist between the cloud tier and the aggregate.

.About this task

The following object stores can be used as cloud tiers:

* StorageGRID
* Alibaba Cloud (Starting with System Manager 9.6)
* Amazon Web Services (AWS) Simple Storage Service (S3)
* Amazon Web Services (AWS) Commercial Cloud Service (C2S)
* Microsoft Azure Blob storage
* IBM Cloud
* Google Cloud

[NOTE]
====

* Azure Stack, which is an on-premises Azure services, is not supported.
* If you want to use any object store as a cloud tier, other than StorageGRID, you must have the FabricPool capacity license.

====

.Steps

. Create a FabricPool-enabled aggregate by using one of the following methods:
 ** Click *Applications & Tiers* > *Storage Tiers* > *Add Aggregate*.
 ** Click *Storage* > *Aggregate & Disks* > *Aggregates* > *Create*.
. Enable the *Manually Create Aggregate* option to create an aggregate.
. Create a FabricPool-enabled aggregate:
 .. Specify the name of the aggregate, the disk type, and the number of disks or partitions to include in the aggregate.
+
[NOTE]
====
Only all flash (all SSD) aggregates support FabricPool-enabled aggregates.
====
+
The minimum hot spare rule is applied to the disk group that has the largest disk size.

 .. Modify the RAID configuration of the aggregate:
  ... Click *Change*.
  ... In the Change RAID Configuration dialog box, specify the RAID type and the RAID group size.
+
Shared disks support two RAID types: RAID-DP and RAID-TEC.

  ... Click *Save*.
. Select the *FabricPool* checkbox, and then select a cloud tier from the list.
. Click *Create*.
