---
permalink: online-help-96-97/task_deleting_local_windows_group.html
sidebar: sidebar
keywords: delete, local, windows, group, systems, manager, online, help, svm, rights
summary: "You can use System Manager to delete a local Windows group from a storage virtual machine (SVM) if the group is no longer required for determining access rights to the data contained on the SVM or for assigning SVM user rights (privileges) to group members."
---
= Deleting a local Windows group
:icons: font
:imagesdir: ../media/

[.lead]
You can use System Manager to delete a local Windows group from a storage virtual machine (SVM) if the group is no longer required for determining access rights to the data contained on the SVM or for assigning SVM user rights (privileges) to group members.

== About this task

* Removing a local group removes the membership records of the group.
* The file system is not altered.
+
Windows Security Descriptors on files and directories that refer to this group are not adjusted.

* The special "`Everyone`" group cannot be deleted.
* Built-in groups such as BUILTIN\Administrators and BUILTIN\Users cannot be deleted.

== Steps

. Click *Storage* > *SVMs*.
. Select the SVM, and then click *SVM Settings*.
. In the *Host Users and Groups* pane, click *Windows*.
. In the *Groups* tab, select the group that you want to delete, and then click *Delete*.
. Click *Delete*.

== Results

The local group is deleted along with its membership records.

*Related information*

xref:reference_windows_window.adoc[Windows window]
