---
permalink: online-help-96-97/task_editing_vault_relationships.html
sidebar: sidebar
keywords: edit, vault, relationships, system, manager, online, help, cluster, schedule
summary: "You can use System Manager to edit a vault relationship either by selecting an existing policy or schedule in the cluster, or by creating a new policy or schedule. However, you cannot edit the parameters of an existing policy or schedule."
---
= Editing vault relationships
:icons: font
:imagesdir: ../media/

[.lead]
You can use System Manager to edit a vault relationship either by selecting an existing policy or schedule in the cluster, or by creating a new policy or schedule. However, you cannot edit the parameters of an existing policy or schedule.

== Before you begin

The source and destination clusters must be in a healthy peer relationship.

== Steps

. Click *Protection* > *Volume Relationships*.
. Select the vault relationship for which you want to modify the policy or schedule, and then click *Edit*.
. In the *Edit Relationship* dialog box, select the appropriate action:
+
[options="header"]
|===
| If you want to...| Do the following...
a|
Select an existing policy
a|
Click *Browse*, and then select an existing policy.    You can select a policy that has the maximum number of matching labels with the Snapshot policy that is attached to the source volume.
a|
Create a new policy
a|

 .. Click *Create Policy*.
 .. Specify a name for the policy.
 .. Set the priority for scheduled transfers.
+
Low indicates that the transfer has the least priority and is usually scheduled after normal priority transfers. By default, the priority is set to Normal.

 .. Select the *Enable Network Compression* check box to compress the data that is being transferred.
 .. Specify a SnapMirror label and destination retention count for the vault policy.
+
You must ensure that a Snapshot copy with the same label is created on the source volume for the new SnapMirror label to be effective.

 .. Click *Create*.

|===

. Specify a schedule for the relationship:
+
[options="header"]
|===
| If...| Do the following...
a|
You want to assign an existing schedule
a|
Select an existing schedule from the list.
a|
You want to create a new schedule
a|

 .. Click *Create Schedule*.
 .. Specify a name for the schedule.
 .. Select one of the following options:
  *** *Basic*
+
You can select this option to specify only the day of the week, time, and the transfer interval.

  *** *Advanced*
+
You can select this option to specify a cron-style schedule.
 .. Click *Create*.

a|
You do not want to assign a schedule
a|
Select *None*.
|===

. Click *OK*.

*Related information*

xref:reference_protection_window.adoc[Protection window]
