---
permalink: online-help-96-97/task_resynchronizing_mirror_relationships.html
sidebar: sidebar
keywords: resync
summary: 'You can reestablish a mirror relationship that was broken earlier. You can perform a resynchronization operation to recover from a disaster that disabled the source volume.'
---
= Resynchronizing mirror relationships
:icons: font
:imagesdir: ../media/

[.lead]
You can reestablish a mirror relationship that was broken earlier. You can perform a resynchronization operation to recover from a disaster that disabled the source volume.

The source cluster and destination cluster and the source SVM and destination SVM must be in peer relationships.

* When you perform a resynchronization operation, the contents on the mirror destination are overwritten by the contents on the source volume.
+
[NOTE]
====
+
....
-   For SnapLock compliance volumes, all data changes in the active file system with reference to the common Snapshot copy are preserved in a locked Snapshot copy until the expiry time that is set for the current volume.

    If the volume expiry time is in the past or has not been set, then the Snapshot copy and the common Snapshot copy are locked for a duration of 30 days. All of the intermediate Snapshot copies between the common Snapshot copy and the latest locked Snapshot copy are deleted.

-   For all volumes other than SnapLock compliance volumes, the resynchronization operation might cause loss of newer data that is written to the destination volume after the base Snapshot copy was created.
....
+
====

* If the Last Transfer Error field in the Protection window recommends a resynchronization operation, you must first break the relationship, and then perform the resynchronization operation.

. Click *Protection* > *Volume Relationships*.
. Select the mirror relationship that you want to resynchronize.
. Click *Operations* > *Resync*.
. Select the confirmation checkbox, and then click *Resync*.

*Related information*

xref:reference_protection_window.adoc[Protection window]
