---
permalink: online-help-96-97/task_changing_the_status_of_a_volume.html
sidebar: sidebar
keywords: 
summary: 'You can use System Manager to change the status of a FlexVol volume when you want to take a volume offline, bring a volume back online, or restrict access to a volume.'
---
= Changing the status of a volume
:icons: font
:imagesdir: ../media/

[.lead]
You can use System Manager to change the status of a FlexVol volume when you want to take a volume offline, bring a volume back online, or restrict access to a volume.

* If you want a volume to be the target of a volume copy operation or a SnapMirror replication operation, the volume must be in the restricted state.
* If you want to take a NAS volume offline, the NAS volume must be unmounted.

You can take a volume offline to perform maintenance on the volume, to move the volume, or to destroy the volume. When a volume is offline, the volume is unavailable for read or write access by clients. You cannot take a root volume offline.

. Click *Storage* > *Volumes*.
. From the drop-down menu in the *SVM* field, select *All SVMs*.
. Select the volume for which you want to modify the status.
. From the *More Actions* > *Change status to* menu, select the required volume status.
. Click *Ok* in the confirmation dialog box to change the volume status.

*Related information*

xref:reference_volumes_window_stm_topic.adoc[Volumes window]
