---
permalink: online-help-96-97/task_creating_nvme_subsystems.html
sidebar: sidebar
keywords: 
summary: 'You can use System Manager to create an NVMe subsystem.'
---
= Creating NVMe subsystems
:icons: font
:imagesdir: ../media/

[.lead]
You can use System Manager to create an NVMe subsystem.

== Steps

. Click *Create* in the *NVMe Subsystems* window.
. Provide entries in the *NVMe Subsystems: Create* window for the following fields:
 ** *SVM*
+
From the drop-down menu, select the SVM on which you want to create the subsystem.

 ** *Name*
+
Enter a name for the subsystem. The subsystem name cannot already exist in the SVM. The name is case-sensitive and is limited to 96 characters. Special characters are allowed.

 ** *Host OS*
+
From the drop-down menu, select the type of Host OS of the subsystem.

 ** *Host NQN*
+
Enter the Host NQN attached to the controller. You can enter more than one Host NQN by separating them with commas.
. Click *Save*.
+
The NVMe subsystem is created, and the NVMe Subsystemswindow is displayed.

*Related information*

xref:reference_nvme_subsystems_window.adoc[NVMe Subsystems window]
