---
permalink: online-help-96-97/task_creating_cluster_peer_relationships.html
sidebar: sidebar
keywords: system, manager, create, cluster, peer, relationships, online, help
summary: "You can create an authenticated cluster peer relationship to connect clusters so that the clusters in the peer relationship can communicate securely with each other."
---
= Create cluster peer relationships
:icons: font
:imagesdir: ../media/

[.lead]
You can create an authenticated cluster peer relationship to connect clusters so that the clusters in the peer relationship can communicate securely with each other.

.Before you begin

* You must have reviewed and completed the requirements for performing this task.
+
link:reference_prerequisites_for_cluster_peering.md#[Prerequisites for cluster peering]

* You must have created intercluster logical interfaces (LIFs).
* You should be aware of which version of ONTAP each cluster is running.

.About this task

* If you want to create a peer relationship with a cluster running Data ONTAP 8.2.2 or earlier, you must use the CLI.
* You can create a peer relationship between a cluster running ONTAP 9.5 and a cluster running ONTAP 9.6. However, encryption is not supported in ONTAP 9.5, so the peer relationship cannot be encrypted.
* In a MetroCluster configuration, when you create a peer relationship between the primary cluster and an external cluster, it is a best practice to create a peer relationship between the surviving site cluster and the external cluster as well.
* You can create a custom passphrase or you can use the system-generated passphrase to authenticate the cluster peer relationship. However, the passphrases of both clusters must match.

.Steps

. Click *Configuration* > *Advanced Cluster Setup*.
. In the *Target Cluster Intercluster LIF IP addresses* field, enter the IP addresses of the remote cluster's intercluster LIFs.
. If you are creating a peer relationship between a cluster running ONTAP 9.5 and a cluster running ONTAP 9.6, select the checkbox.
+
The peer relationship will not be encrypted. If you do not select the checkbox, the peer relationship will not be established.

. In the *Passphrase* field, specify a passphrase for the cluster peer relationship.
+
If you create a custom passphrase, the passphrase will be validated against the passphrase of the peered cluster to ensure an authenticated cluster peer relationship.
+
If the names of the local cluster and remote cluster are identical, and if you are using a custom passphrase, an alias is created for the remote cluster.

. To generate a passphrase from the remote cluster, enter the management IP address of the remote cluster.
. Initiate cluster peering.
+
[options="header"]
|===
| If you want to...| Do this...
a|
Initiate cluster peering from the initiator cluster
a|
Click *Initiate Cluster Peering*.
a|
Initiate cluster peering from the remote cluster    (Applicable if you have created a custom passphrase)
a|

 .. Enter the management IP address of the remote cluster.
 .. Click the *Management URL* link to access the remote cluster.
 .. Click *Create Cluster Peering*.
 .. Specify the intercluster LIF IP addresses and passphrase of the initiator cluster.
 .. Click *Initiate Peering*.
 .. Access the initiator cluster, and then click *Validate Peering*.

|===

== What to do next

You should specify the SVM details in the SVM Peering window to continue with the peering process.
