---
permalink: online-help-96-97/task_managing_svm_relationships.html
sidebar: sidebar
keywords: 
summary: 'You can use System Manager to perform various operations on SVM relationships such as initializing SVM relationships, updating SVM relationships, activating the destination SVM, resynchronizing data from the source SVM, resynchronizing data from the destination SVM, and reactivating the source SVM.'
---
= Managing SVM relationships
:icons: font
:imagesdir: ../media/

[.lead]
You can use System Manager to perform various operations on SVM relationships such as initializing SVM relationships, updating SVM relationships, activating the destination SVM, resynchronizing data from the source SVM, resynchronizing data from the destination SVM, and reactivating the source SVM.

== Before you begin

* To initialize the SVM relationship, the source and destination clusters must be in a healthy peer relationship.
* To update the SVM relationship, the SVM relationship must be initialized and in a Snapmirrored state.
* To reactivate the source SVM, the resynchronize data from the destination SVM (reverse resync) operation must have been performed.
* If you had selected the option to copy the source SVM configuration while creating the SVM relationship, then to activate the SVM relationship, the source SVM must be stopped.
* SnapMirror license must be enabled on the source cluster and destination cluster.
* The source cluster and destination cluster must be in a healthy peer relationship.
* The destination cluster must have space available.
* The source SVM must have permission for SVM peering.
* You must break the SVM relationship to activate destination SVM, resync from source SVM, resync from destination SVM (Reverse Resync), and reactivate source SVM.
* To reactivate the source SVM, the SVM reverse relationship must exist and be in a Snapmirrored state.

== Steps

. Click *Protection* > *SVM Relationship*.
. Select the SVM relationship, and then perform the appropriate action:
+
|===
| If you want to...| Do the following...
a|
Initialize the SVM relationship
a|

 .. Click *Operations* > *Initialize*.
+
The Initialize dialog box is displayed.

 .. Click *Initialize*.

a|
Update the SVM relationship
a|

 .. Click *Operations* > *Update*.
+
The Update dialog box is displayed.

 .. Click *Update*.

a|
Activate the destination SVM    Activating the destination SVM involves quiescing scheduled SnapMirror transfers, aborting any ongoing SnapMirror transfers, breaking the SVM relationship, and starting the destination SVM.
a|

 .. Click *Operations* > *Activate Destination SVM*.
+
The Activate Destination SVM dialog box is displayed.

 .. Select the *Ok to activate destination SVM and break the relationship* checkbox.
 .. Click *Activate*.

a|
Resynchronize data from the source SVM    The resync operation performs a rebaseline of the SVM configuration. You can resync from the source SVM to reestablish a broken relationship between the two SVMs. When the resync is complete, the destination SVM contains the same information as the source SVM and is scheduled for further updates.
a|

 .. Click *Operations* > *Resync from Source SVM*.
+
The Resync from Source SVM dialog box is displayed.

 .. Select the *Ok to delete any newer data in the destination SVM* checkbox.
 .. Click *Resync*.

a|
Resynchronize data from the destination SVM (Reverse Resync)    You can resync from the destination SVM to create a new relationship between the two SVMs. During this operation, the destination SVM continues to serve data with the source SVM backing up the configuration and data of the destination SVM.
a|

 .. Click *Operations* > *Resync from Destination SVM (Reverse ReSync)*.
+
The Resync from Destination SVM (Reverse Resync) dialog box is displayed.

 .. If the SVM has multiple relationships, select the *This SVM has multiple relationships, Ok to release to other relationships* checkbox.
 .. Select the *Ok to delete the new data in the source SVM* checkbox.
 .. Click *Reverse Resync*.

a|
Reactivate the source SVM    Reactivating the source SVM involves protecting and recreating the SVM relationships between the source and destination SVM. If you had selected the option to copy the source SVM configuration while creating the SVM relationship, then the destination SVM will stop processing data.
a|

 .. Click *Operations* > *Reactivate Source SVM*.
+
The Reactivate Source SVM dialog box is displayed.

 .. Click *Initiate Reactivation* to initiate reactivation to the destination SVM.
 .. Click *Done*.

+
|===
