---
permalink: online-help-96-97/task_deleting_vault_relationships.html
sidebar: sidebar
keywords: 
summary: 'You can use System Manager to end a vault relationship between a source and destination volume, and release the Snapshot copies from the source.'
---
= Deleting vault relationships
:icons: font
:imagesdir: ../media/

[.lead]
You can use System Manager to end a vault relationship between a source and destination volume, and release the Snapshot copies from the source.

Releasing the relationship permanently removes the base Snapshot copies used by the vault relationship on the source volume. To re-create the vault relationship, you must run the resynchronization operation from the source volume by using the command-line interface (CLI).

. Click *Protection* > *Volume Relationships*.
. Select the volume for which you want to delete the vault relationship, and click *Delete*.
. Select the confirmation check box, and then click *Delete*.
+
You can also select the release base Snapshot copies check box to delete the base Snapshot copies used by the vault relationship on the source volume.
+
If the relationship is not released, then you must use the CLI to run the release operation on the source cluster to delete the base Snapshot copies that were created for the vault relationship from the source volume.

*Related information*

xref:reference_protection_window.adoc[Protection window]
