---
permalink: nfs-config-esxi/reference_where_to_find_additional_information.html
sidebar: sidebar
keywords: successful, test, nfs, client, access, configuration, san, protocol, complete, protect, root, volume, comprehensive, guide, technical, report, goal, where to find additional information
summary: "After you have successfully tested NFS client access, you can perform additional NFS configuration or add SAN access. When protocol access is complete, you should protect the root volume of the . There are express guides, comprehensive guides, and technical reports to help you achieve these goals."
---
= Where to find additional information
:icons: font
:imagesdir: ../media/

[.lead]
After you have successfully tested NFS client access, you can perform additional NFS configuration or add SAN access. When protocol access is complete, you should protect the root volume of the . There are express guides, comprehensive guides, and technical reports to help you achieve these goals.

== NFS configuration

You can further configure NFS access using the following comprehensive guides and technical reports:

* https://docs.netapp.com/us-en/ontap/nfs-config/index.html[NFS configuration]
+
Describes how to use CLI commands to configure advanced NFS client access to files contained in a new volume or qtree.

* https://docs.netapp.com/us-en/ontap/nfs-admin/index.html[NFS management]
+
Describes how to manage file access using the NFS protocol, including authentication, authorization, and security.

* http://www.netapp.com/us/media/tr-4597.pdf[NetApp Technical Report 4597: VMware vSphere with ONTAP]
+
Describes the best practices that should be followed when using ONTAP and VMware vSphere server virtualization environments.

* https://www.netapp.com/pdf.html?item=/media/16328-tr-4668pdf.pdf[NetApp Technical Report 4668: Name Services Best Practices Guide]
+
Provides a comprehensive list of best practices, limits, recommendations, and considerations when configuring LDAP, NIS, DNS, and local user and group files for authentication purposes.

* http://www.netapp.com/us/media/tr-4067.pdf[NetApp Technical Report 4067: NFS Best Practice and Implementation Guide]
+
Provides an overview of ONTAP with a focus on NFSv4.

== Root volume protection

After configuring protocols on the SVM, you should ensure that its root volume is protected:

* https://docs.netapp.com/us-en/ontap/data-protection/index.html[Data protection]
+
Describes how to create a load-sharing mirror to protect the root volume, which is a NetApp best practice for NAS-enabled SVMs. Also describes how to quickly recover from volume failures or losses by promoting the SVM root volume from a load-sharing mirror.
