---
permalink: fc-config-esxi/concept_deciding_whether_to_use_this_guide_fc_esx.html
sidebar: sidebar
keywords: 
summary: 'This guide describes how to quickly set up the FC service on a storage virtual machine \(SVM\), provision a LUN, and make the LUN available as a datastore using an FC HBA on an ESX host computer.'
---
= Deciding whether to use the FC Configuration for ESX Express Guide
:icons: font
:imagesdir: ../media/

[.lead]
This guide describes how to quickly set up the FC service on a storage virtual machine (SVM), provision a LUN, and make the LUN available as a datastore using an FC HBA on an ESX host computer.

This guide is based on the following assumptions:

* You want to use best practices, not explore every available option.
* You do not want to read a lot of conceptual background.
* You want to use System Manager, not the ONTAP command-line interface or an automated scripting tool.
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help/GUID-DF04A607-30B0-4B98-99C8-CB065C64E670.html[ONTAP 9 Cluster Management Using OnCommand System Manager]

* You want to use the _legacy_ OnCommand System Manager UI for ONTAP 9.7 and earlier releases, not the ONTAP System Manager UI for ONTAP 9.7 and later.
+
https://docs.netapp.com/us-en/ontap/[ONTAP System Manager documentation]

* You are using a supported version of Virtual Storage Console for VMware vSphere to configure storage settings for your ESX host and to provision the datastores.
* Your network uses IPv4 addressing.
* You are using traditional FC HBAs on ESXi 5.x and traditional FC switches.
+
This guide does not cover FCoE.

* You have at least two FC target ports available on each node in the cluster.
+
Onboard FC and UTA2 (also called "`CNA`") ports, as well as some adapters are configurable. Configuring those ports is done in the ONTAP CLI and is not covered in this guide.

* You are not configuring FC SAN boot.
* You are creating datastores on the host.
+
This guide does not cover raw device mapping (RDM) disks or using N-port ID virtualization (NPIV) to provide FC directly to VMs.

If these assumptions are not correct for your situation, you should see the following resources:

* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanag/home.html[ONTAP 9 SAN Administration Guide]
* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanconf/home.html[ONTAP 9 SAN Configuration Guide]
* https://docs.netapp.com/vapp-96/topic/com.netapp.doc.vsc-iag/home.html[Appliance administration]
* _VMware vSphere Storage_ for your version of ESXi 5 (available from VMware).
+
http://www.vmware.com[VMware]

* http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61550[NetApp Documentation: OnCommand Workflow Automation (current releases)]
+
OnCommand Workflow Automation enables you to run prepackaged workflows that automate management tasks such as the workflows described in Express Guides.
