---
permalink: fc-config-esxi/task_updating_the_hba_firmware.html
sidebar: sidebar
keywords: 
summary: 'If the FC host bus adapters \(HBAs\) in the ESX host are not running supported driver, firmware, and BIOS versions, you must update them.'
---
= Updating the HBA driver, firmware, and BIOS
:icons: font
:imagesdir: ../media/

[.lead]
If the FC host bus adapters (HBAs) in the ESX host are not running supported driver, firmware, and BIOS versions, you must update them.

You must have identified the supported driver, firmware, and BIOS versions for your configuration from the https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool].

Drivers, firmware, BIOS, and HBA utilities are provided by the HBA vendors.

. List the installed HBA driver, firmware, and BIOS versions using the ESXi host console commands for your version of ESXi.
. Download and install the new driver, firmware, and BIOS as needed from the HBA vendor's support site.
+
Installation instructions and any required installation utilities are available with the download.

*Related information*

http://kb.vmware.com/kb/1002413[VMware KB article 1002413: Identifying the firmware of a Qlogic or Emulex FC HBA]
