---
permalink: fc-config-esxi/task_installing_virtual_storage_console_for_vmware_vsphere.html
sidebar: sidebar
keywords: virutal, storage, console, vsc, vmware, vsphere, automate, configuration, provision, task, require, netapp, fc, storage, esxi, host, plug-in, vcenter, server, install virtual storage console
summary: "Virtual Storage Console for VMware vSphere automates many of the configuration and provisioning tasks required to use NetApp FC storage with an ESXi host. Virtual Storage Console is a plug-in to vCenter Server."
---
= Install Virtual Storage Console
:icons: font
:imagesdir: ../media/

[.lead]
Virtual Storage Console for VMware vSphere automates many of the configuration and provisioning tasks required to use NetApp FC storage with an ESXi host. Virtual Storage Console is a plug-in to vCenter Server.

.Before you begin

You must have administrator credentials on the vCenter Server used to manage the ESXi host.

.About this task

* Virtual Storage Console is installed as a virtual appliance that includes Virtual Storage Console, vStorage APIs for Storage Awareness (VASA) Provider, and Storage Replication Adapter (SRA) for VMware vSphere capabilities.

.Steps

. Download the version of Virtual Storage Console that is supported for your configuration, as shown in the Interoperability Matrix tool.
+
https://mysupport.netapp.com/site/global/dashboard[NetApp Support]

. Deploy the virtual appliance and configure it following the steps in the _Deployment and Setup Guide_.
