---
permalink: fc-config-rhel/index.html
sidebar: sidebar
keywords: quick, set, up, fc, service, storage, virtual, machine, svm, provision, lun, fc, host, bus, adapter, hba, red, hat, enterprise, linux, server, configuration
summary: "This content describes how to quickly set up the FC service on a storage virtual machine, provision a LUN, and make the LUN available using an FC host bus adapter on a Red Hat Enterprise Linux server."
---
= FC configuration for Red Hat Enterprise Linux overview
:icons: font
:imagesdir: ../media/

[.lead]
This content describes how to quickly set up the FC service on a storage virtual machine (SVM), provision a LUN, and make the LUN available using an FC host bus adapter (HBA) on a Red Hat Enterprise Linux server.

This content is based on the following assumptions:

* You want to use best practices, not explore every available option.
* You do not want to read a lot of conceptual background.
* You want to use the _Classic_ System Manager UI for ONTAP 9.7 and earlier releases, not the ONTAP System Manager UI for ONTAP 9.7 and later.
+
https://docs.netapp.com/us-en/ontap/[ONTAP System Manager documentation^]

* The host is running a supported version of Red Hat Enterprise Linux 6.4 or later.
* You are using traditional FC HBAs and switches.
+
This content does not cover Fibre Channel over Ethernet (FCoE).

* You have at least two FC target ports available on each node in the cluster.
+
Onboard FC and UTA2 (also called "`CNA`") ports, as well as some adapters, are configurable. Configuring those ports is done in the ONTAP command-line interface (CLI) and is not covered in this content.

* You are not configuring FC SAN boot.

If these assumptions are not correct for your situation, you should see the following resources:

* https://docs.netapp.com/us-en/ontap/san-admin/index.html[SAN administration^]
* https://docs.netapp.com/us-en/ontap/san-config/index.html[SAN configuration^]
* https://docs.netapp.com/us-en/ontap-sanhost/hu_luhu_71.html[Linux Unified Host Utilities 7.1 Installation^]
