---
permalink: iscsi-config-rhel/task_linux_configuring_logical_volumes_on_multipath_devices_and_creating_a_file_system.html
sidebar: sidebar
keywords: 
summary: 'When the Linux host first accesses a new SCSI device \(LUN\), there is no partition or file system. If you want to use a partitioned multipath device, you must first partition the underlying SCSI devices. You might also want to create logical volumes on multipath devices, and optionally create a file system.'
---
= Configuring logical volumes on multipath devices and creating a file system
:icons: font
:imagesdir: ../media/

[.lead]
When the Linux host first accesses a new SCSI device (LUN), there is no partition or file system. If you want to use a partitioned multipath device, you must first partition the underlying SCSI devices. You might also want to create logical volumes on multipath devices, and optionally create a file system.

SCSI devices and corresponding multipath devices must have been discovered by the Linux host.

At a minimum DM-Multipath should be configured on the SCSI devices. Any configuration beyond DM-Multipath is optional. The following steps are general guidelines if you wish to perform additional configuration, such as partitioning, configuring logical volumes on multipath devices, and creating a file system. For details on Linux commands, refer to Red Hat Enterprise Linux documentation and man pages.

. To use a partitioned multipath device, first partition the underlying SCSI devices using the `fdisk` or `parted` utility.
. Create corresponding multipath partitions using the `kpartx` utility.
. Create logical volumes on corresponding multipath devices using Logical Volume Manager (LVM) commands.
. Create a file system, such as Ext4 or XFS, on logical volumes or multipath devices using the `mkfs` utility.
