---
permalink: iscsi-config-windows/reference_where_to_find_additional_information.html
sidebar: sidebar
keywords: document, iscsi, configuration, where to find additional information
summary: There are additional documents to help you learn more about iSCSI configuration.
---
= Where to find additional information
:icons: font
:imagesdir: ../media/

[.lead]
There are additional documents to help you learn more about iSCSI configuration.

All of the following documentation is available:

* https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanconf/home.html[SAN configuration]
+
Describes supported FC, iSCSI, and FCoE topologies for connecting host computers to storage controllers in clusters.

* https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanag/home.html[SAN administration]
+
Describes how to configure and manage the iSCSI, FCoE, and FC protocols for clustered SAN environments, including configuration of LUNs, igroups, and targets.

== Microsoft documentation

Documentation about the Microsoft iSCSI software initiator is available directly from Microsoft.

* _Microsoft iSCSI Software Initiator Version 2.X Users Guide_
+
Describes the Microsoft iSCSI software initiator for Windows Server 2008. It is included with the iSCSI software initiator download files.

* _Microsoft iSCSI Initiator Overview_
+
Online Help for the Windows Server 2012 iSCSI initiator (available from within the initiator). Describes the software initiator and includes links to the Microsoft web site for further information.

*Related information*

http://www.microsoft.com[Microsoft]
