---
permalink: iscsi-config-windows/task_verifying_that_iscsi_fc_configuration_is_supported.html
sidebar: sidebar
keywords: reliable, operation, verify, iscsi, configuration, support, verify that the iscsi configuration is supported
summary: "For reliable operation, you must verify that the entire iSCSI configuration is supported."
---
= Verify that the iSCSI configuration is supported
:icons: font
:imagesdir: ../media/

[.lead]
For reliable operation, you must verify that the entire iSCSI configuration is supported.

.Steps

. Go to the Interoperability Matrix to verify that you have a supported combination of the following components:
 ** ONTAP software
 ** Host computer CPU architecture (for standard rack servers)
 ** Specific processor blade model (for blade servers)
 ** Storage protocol (iSCSI)
 ** Windows operating system version
 ** Windows Unified Host Utilities
. Click the configuration name for the selected configuration.
+
Details for that configuration are displayed in the Configuration Details window.

. Review the information in the following tabs:
 ** Notes
+
Lists important alerts and information that are specific to your configuration.
+
Review the alerts to identify the hotfixes that are required for your operating system.

 ** Policies and Guidelines
+
Provides general guidelines for all SAN configurations.
