---
permalink: volume-disaster-recovery/concept_deciding_whether_to_use_the_volume_disaster_recovery_express_guide.html
sidebar: sidebar
keywords: 
summary: 'This guide describes how to quickly activate a destination volume after a disaster and then reactivate the source volume in ONTAP.'
---
= Deciding whether to use the Volume Disaster Recovery Express Guide
:icons: font
:imagesdir: ../media/

[.lead]
This guide describes how to quickly activate a destination volume after a disaster and then reactivate the source volume in ONTAP.

You should use this guide if you want to perform a volume-level disaster recovery procedure in the following way:

* You are working with clusters running ONTAP 9.
* You are a cluster administrator.
* You have configured the SnapMirror relationship following the _Volume Disaster Recovery Preparation Express Guide_.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-sm-ic-cg/home.html[Volume disaster recovery express preparation]

* The cluster administrator of the source cluster has declared that the data in the source volume is unavailable due to events such as virus infection leading to data corruption or accidental deletion of data.
* You want to use System Manager, not the ONTAP command-line interface or an automated scripting tool.
* You want to use the _legacy_ OnCommand System Manager UI for ONTAP 9.7 and earlier releases, not the ONTAP System Manager UI for ONTAP 9.7 and later.
+
https://docs.netapp.com/us-en/ontap/[ONTAP System Manager documentation]

* You want to use best practices, not explore every available option.
* You do not want to read a lot of conceptual background.

If these assumptions are not correct for your situation, or if you want more conceptual background information, you should see the following resources:

* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-dap/home.html[Data protection]
* https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-vsmg/home.html[Logical storage management]
* http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61550[NetApp Documentation: OnCommand Workflow Automation (current releases)]
+
OnCommand Workflow Automation enables you to run prepackaged workflows that automate management tasks such as the workflows described in Express Guides.
