---
permalink: volume-disaster-recovery/index.html
sidebar: sidebar
keywords: content, destination, activate, volume, disaster, reactivate, source, ontap, volume disaster recovery overview
summary: "This content describes how to quickly activate a destination volume after a disaster and then reactivate the source volume in ONTAP."
---
= Volume disaster recovery overview
:icons: font
:imagesdir: ../media/

[.lead]
This content describes how to quickly activate a destination volume after a disaster and then reactivate the source volume in ONTAP.

You should use this content if you want to perform a volume-level disaster recovery procedure in the following way:

* You are working with clusters running ONTAP 9.
* You are a cluster administrator.
* You have configured the SnapMirror relationship following link:/../volume-disaster-prep/index.html[Volume disaster recovery preparation]

* The cluster administrator of the source cluster has declared that the data in the source volume is unavailable due to events such as virus infection leading to data corruption or accidental deletion of data.
* You want to use System Manager, not the ONTAP command-line interface or an automated scripting tool.
* You want to use the _Classic_ System Manager UI for ONTAP 9.7 and earlier releases, not the ONTAP System Manager UI for ONTAP 9.7 and later.
+
https://docs.netapp.com/us-en/ontap/[ONTAP System Manager documentation^]

* You want to use best practices, not explore every available option.
* You do not want to read a lot of conceptual background.

If these assumptions are not correct for your situation, or if you want more conceptual background information, you should see the following resources:

* https://docs.netapp.com/us-en/ontap/data-protection/index.html[Data protection^]
* https://docs.netapp.com/us-en/ontap/volumes/index.html[Logical storage management^]
