---
permalink: peering/index.html
sidebar: sidebar
keywords: cluster, administrator, create, authenticated, peer, relationship, svm, enable, communicate, replicate, data
summary: "This content describes how cluster administrators create authenticated peer relationships between clusters and SVMs to enable the clusters to communicate with each other so that you can replicate data between volumes in different clusters."
---
= Cluster and SVM peering overview
:icons: font
:imagesdir: ../media/

[.lead]
This content describes how cluster administrators create authenticated peer relationships between clusters and SVMs to enable the clusters to communicate with each other so that you can replicate data between volumes in different clusters.

ONTAP System Manager in ONTAP 9.3 simplifies the way that you configure peer relationships between clusters and between SVMs. This content describes the cluster peering procedure and SVM peering procedure for all ONTAP 9 versions. You should use the appropriate procedure for your version of ONTAP.

You should use this content if you want to create cluster peer relationships and SVM peer relationships in the following way:

* You are working with clusters running ONTAP 9.
* You want cluster peering relationships that are authenticated.
* You want to use best practices, not explore every available option.
* You do not want to read a lot of conceptual background.
* You want to use System Manager, not the ONTAP command-line interface or an automated scripting tool.
* You want to use the _Classic_ System Manager UI for ONTAP 9.7 and earlier releases, not the ONTAP System Manager UI for ONTAP 9.7 and later.
+
https://docs.netapp.com/us-en/ontap/[ONTAP System Manager documentation]

If these assumptions are not correct for your situation, you should see the following resources:

* https://docs.netapp.com/us-en/ontap/peering/index.html[Cluster and SVM peering]
+
Describes how to use the command-line interface to set up cluster peering relationships and SVM peering relationships.

* https://docs.netapp.com/us-en/ontap/networking/index.html[Network management]
+
Describes how to use the command-line interface to configure subnets, intercluster LIFs, routes, firewall policies, and other networking components.

* http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61550[NetApp Documentation: OnCommand Workflow Automation (current releases)]
+
OnCommand Workflow Automation enables you to run prepackaged workflows that automate management tasks.

*Related information*

https://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help/GUID-DF04A607-30B0-4B98-99C8-CB065C64E670.html[Cluster management using System Manager]
