---
permalink: smb-config/concept_smb_config_overview.html
sidebar: sidebar
keywords: 
summary: 'This guide describes how to quickly set up SMB/CIFS access to a new volume on either a new or existing storage virtual machine \(SVM\).'
---
= Deciding whether to use the SMB/CIFS Configuration Express Guide
:icons: font
:imagesdir: ../media/

[.lead]
This guide describes how to quickly set up SMB/CIFS access to a new volume on either a new or existing storage virtual machine (SVM).

You should use this guide if you want to configure access to a volume in the following way:

* You want to use best practices, not explore every available option.
* You do not want to read a lot of conceptual background.
* You want to use System Manager, not the ONTAP command-line interface or an automated scripting tool.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help/GUID-DF04A607-30B0-4B98-99C8-CB065C64E670.html[Cluster management using System Manager]

* You want to use the _legacy_ OnCommand System Manager UI for ONTAP 9.7 and earlier releases, not the ONTAP System Manager UI for ONTAP 9.7 and later.
+
https://docs.netapp.com/us-en/ontap/[ONTAP System Manager documentation]

* Your data network uses the default IPspace, the default broadcast domain, and the default failover group.
+
If your data network is flat, using these default objects ensures that LIFs will fail over correctly in the event of a link failure. If you are not using the default objects, you should refer to the _Network Management Guide_ for information on how to configure LIF path failover.

* NTFS file permissions will be used to secure the new volume.

If this guide is not suitable for your situation, you should see the following documentation instead:

* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.cdot-famg-cifs/home.html[SMB/CIFS management]
* https://docs.netapp.com/us-en/ontap/networking/index.html[Network management]
* https://www.netapp.com/pdf.html?item=/media/19384-tr-4616.pdf[NetApp Technical Report 4616: NFS Kerberos in ONTAP with Microsoft Active Directory]
* https://www.netapp.com/pdf.html?item=/media/19423-tr-4835.pdf[NetApp Technical Report 4835: How to Configure LDAP in ONTAP]
* http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61550[NetApp Documentation: OnCommand Workflow Automation (current releases)]
+
OnCommand Workflow Automation enables you to run prepackaged workflows that automate management tasks such as the workflows described in Express Guides.
