---
permalink: smb-config/index.html
sidebar: sidebar
keywords: content, describe, smb, cifs, access, volume, exist, storage, virtual, machine, svm
summary: "This content describes how to quickly set up SMB/CIFS access to a new volume on either a new or existing storage virtual machine (SVM)."
---
= SMB/CIFS configuration overview
:icons: font
:imagesdir: ../media/

[.lead]
This content describes how to quickly set up SMB/CIFS access to a new volume on either a new or existing storage virtual machine (SVM).

You should use this content if you want to configure access to a volume in the following way:

* You want to use best practices, not explore every available option.
* You do not want to read a lot of conceptual background.
* You want to use the _Classic_ System Manager UI for ONTAP 9.7 and earlier releases, not the ONTAP System Manager UI for ONTAP 9.7 and later.
+
https://docs.netapp.com/us-en/ontap/[ONTAP System Manager documentation]

* Your data network uses the default IPspace, the default broadcast domain, and the default failover group.
+
If your data network is flat, using these default objects ensures that LIFs will fail over correctly in the event of a link failure. If you are not using the default objects, you should refer to the https://docs.netapp.com/us-en/ontap/networking/index.html[Network Management] for information on how to configure LIF path failover.

* NTFS file permissions will be used to secure the new volume.

If this content is not suitable for your situation, you should see the following documentation instead:

* https://docs.netapp.com/us-en/ontap/smb-admin/index.html[SMB/CIFS management]
* https://docs.netapp.com/us-en/ontap/networking/index.html[Network management]
* https://www.netapp.com/pdf.html?item=/media/19384-tr-4616.pdf[NetApp Technical Report 4616: NFS Kerberos in ONTAP with Microsoft Active Directory]
* https://www.netapp.com/pdf.html?item=/media/19423-tr-4835.pdf[NetApp Technical Report 4835: How to Configure LDAP in ONTAP]
