---
permalink: smb-config/index.html
sidebar: sidebar
keywords: content, describe, smb, cifs, access, volume, exist, storage, virtual, machine, svm, system manager classic
summary: "This content describes how to quickly set up SMB/CIFS access to a new volume on either a new or existing storage virtual machine (SVM) using the ONTAP System Manager classic interface, which is available with ONTAP 9.7 and earlier ONTAP 9 releases."
---
= SMB/CIFS configuration overview
:icons: font
:imagesdir: ../media/

[.lead]
This content describes how to quickly set up SMB/CIFS access to a new volume on either a new or existing storage virtual machine (SVM) using the ONTAP System Manager classic interface, which is available with ONTAP 9.7 and earlier ONTAP 9 releases.

Use this content if you want to configure access to a volume in the following way:

* You want to use best practices, not explore every available option.
* Your data network uses the default IPspace, the default broadcast domain, and the default failover group.
+
If your data network is flat, using these default objects ensures that LIFs will fail over correctly in the event of a link failure. If you are not using the default objects, you should refer to the https://docs.netapp.com/us-en/ontap/networking/index.html[Network management documentation^] for information on how to configure LIF path failover.
* NTFS file permissions will be used to secure the new volume.

== Other ways to do this in ONTAP

[cols=2,options="header"]
|===
| To perform these tasks with... | See this content...
| The redesigned System Manager (available with ONTAP 9.7 and later) | link:https://docs.netapp.com/us-en/ontap/task_nas_provision_windows_smb.html[Provision NAS storage for Windows servers using SMB^]
| The ONTAP command line interface | link:https://docs.netapp.com/us-en/ontap/smb-config/index.html[SMB configuration overview with the CLI^]

|===
