---
permalink: smb-config/reference_where_to_find_additional_information.html
sidebar: sidebar
keywords: successful, test, cifs, client, access, advance, configuration, san, access, protocol, complete, root, volume, svm, comprehensive, technical, report, achieve, goal, where to find additional information
summary: "After you have successfully tested CIFS client access, you can perform advanced CIFS configuration or add SAN access. When protocol access is complete, you should protect the root volume of SVM. There is comprehensive content and technical reports to help you achieve these goals."
---
= Where to find additional information
:icons: font
:imagesdir: ../media/

[.lead]
After you have successfully tested CIFS client access, you can perform advanced CIFS configuration or add SAN access.When protocol access is complete, you should protect the root volume of SVM. There is comprehensive content and technical reports to help you achieve these goals.

== CIFS/SMB configuration

You can further configure CIFS access using the following content and technical reports:

* https://docs.netapp.com/us-en/ontap/smb-admin/index.html[CIFS management^]
+
Describes how to configure and manage file access using the CIFS/SMB protocol.

* http://www.netapp.com/us/media/tr-4191.pdf[NetApp Technical Report 4191: Best Practices for Clustered Data ONTAP 8.2 Windows File Services^]
+
Provides a brief overview of SMB implementation and other Windows File Services features with recommendations and basic troubleshooting information for ONTAP.

* http://www.netapp.com/us/media/tr-3740.pdf[NetApp Technical Report 3740: SMB 2 Next-Generation CIFS Protocol in Data ONTAP^]
+
Describes SMB 2 features, configuration details, and its implementation in ONTAP.

== Root volume protection

After configuring protocols on the SVM, you should ensure that its root volume is protected:

* https://docs.netapp.com/us-en/ontap/data-protection/index.html[Data protection^]
+
Describes how to create a load-sharing mirror to protect the SVM root volume, which is a NetApp best practice for NAS-enabled SVMs. Also describes how to quickly recover from volume failures or losses by promoting the SVM root volume from a load-sharing mirror
