---
permalink: smb-config/task_mapping_the_smb_server_in_the_dns_server.html
sidebar: sidebar
keywords: 
summary: 'Your site’s DNS server must have an entry pointing the SMB server name, and any NetBIOS aliases, to the IP address of the data LIF so that Windows users can map a drive to the SMB server name.'
---
= Mapping the SMB server on the DNS server
:icons: font
:imagesdir: ../media/

[.lead]
Your site's DNS server must have an entry pointing the SMB server name, and any NetBIOS aliases, to the IP address of the data LIF so that Windows users can map a drive to the SMB server name.

You must have administrative access to your site's DNS server. If you do not have administrative access, you must ask the DNS administrator to perform this task.

If you use NetBIOS aliases for the SMB server name, it is a best practice to create DNS server entry points for each alias.

. Log in to the DNS server.
. Create forward (A - Address record) and reverse (PTR - Pointer record) lookup entries to map the SMB server name to the IP address of the data LIF.
. If you use NetBIOS aliases, create an Alias canonical name (CNAME resource record) lookup entry to map each alias to the IP address of the SMB server's data LIF.

After the mapping is propagated across the network, Windows users can map a drive to the SMB server name or its NetBIOS aliases.
