---
permalink: smb-config/task_deciding_where_to_provision_new_volume.html
sidebar: sidebar
keywords:
summary: 'Before you create a new CIFS volume, you must decide whether to place it in an existing storage virtual machine \(SVM\), and, if so, how much configuration the SVM requires. This decision determines your workflow.'
---
= Deciding where to provision the new volume
:icons: font
:imagesdir: ../media/

[.lead]
Before you create a new CIFS volume, you must decide whether to place it in an existing storage virtual machine (SVM), and, if so, how much configuration the SVM requires. This decision determines your workflow.

== Procedure

* If you want to provision a volume on a new SVM, create a new CIFS-enabled SVM.
+
xref:task_creating_protocol_enabled_svm.adoc[Creating a new CIFS-enabled SVM]
+
You must choose this option if CIFS is not enabled on an existing SVM.

* If you want to provision a volume on an existing SVM on which CIFS is enabled but not configured, configure CIFS/SMB access on the existing SVM.
+
xref:task_configuring_access_to_existing_svm.adoc[Configuring CIFS/SMB access on an existing SVM]
+
You should choose this option if you created the SVM for SAN access by using the procedure in this content.

* If you want to provision a volume on an existing SVM that is fully configured for CIFS access, add a CIFS volume to the CIFS-enabled SVM.
+
xref:concept_adding_protocol_volume_to_protocol_enabled_svm.adoc[Adding a CIFS volume to a CIFS-enabled SVM]
