---
permalink: expansion/reference_where_to_find_additional_information.html
sidebar: sidebar
keywords: expand, cluster, storing, store, data, node, volume, exist, guide, achieve, goal, information, express guides, data protection, comprehensive guides, where to find additional information
summary: "After you expand a cluster, you can start storing data on the new nodes either by creating new volumes on the new nodes or by moving existing data to the new nodes. There are express guides and comprehensive documentation to help you achieve these goals."
---
= Where to find additional information
:icons: font
:imagesdir: ../media/

[.lead]
After you expand a cluster, you can start storing data on the new nodes either by creating new volumes on the new nodes or by moving existing data to the new nodes. There are express guides and comprehensive documentation to help you achieve these goals.

== Express guides

If you want to create storage virtual machines (SVMs) or volumes on the newly added nodes, you can use any of the express guides about setting up CIFS, NFS, iSCSI, and FC protocols.

https://docs.netapp.com/ontap-9/index.jsp[ONTAP 9 Documentation Center]

== Data protection

If you are using SnapMirror or SnapVault relationships in your cluster to protect your data, see the http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-clus-peer/home.html[Cluster and SVM peering express configuration] guide to set up appropriate intercluster LIFs for your new nodes.

== Comprehensive guides

If you want to move data to the newly added nodes, you can use the following comprehensive guides:

* https://docs.netapp.com/us-en/ontap/san-admin/index.html[SAN administration]
+
Describes how to configure and manage the iSCSI, FCoE, and FC protocols for clustered SAN environments, including configuration of LUNs, igroups, and targets.

* https://docs.netapp.com/us-en/ontap/volumes/index.html[Logical storage management]
+
Describes how to manage logical storage resources in clusters, including FlexVol volumes, FlexClone volumes, files and LUNs, and FlexCache volumes, using deduplication, compression, qtrees, and quotas.

* https://docs.netapp.com/us-en/ontap/concepts/index.html[ONTAP concepts]
+
Describes conceptual information about logical storage resources in clusters, including FlexVol volumes, FlexClone volumes, files and LUNs, and FlexCache volumes, using deduplication, compression, qtrees, and quotas.
