---
permalink: snmp-config/concept_snmp_config_overview.html
sidebar: sidebar
keywords: content, configure, snmp, cluster, management, level, add, communities, community, security, user, traphost, communication, snmp configuration overview
summary: "This content describes how to configure SNMP at the cluster management level, how to add communities, security users, and traphosts, and how to test the SNMP communication."
---
= SNMP configuration overview
:icons: font
:imagesdir: ../media/

[.lead]
This content describes how to configure SNMP at the cluster management level, how to add communities, security users, and traphosts, and how to test the SNMP communication.

You should use this content if you want to configure SNMP access to a cluster in the following way:

* You are working with clusters running ONTAP 9.
* You want to use best practices, not explore every available option.
* You do not want to read a lot of conceptual background.
* You want to use System Manager, not the ONTAP command-line interface or an automated scripting tool.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help/GUID-DF04A607-30B0-4B98-99C8-CB065C64E670.html[Cluster management using System Manager]
+
[NOTE]
====
There are a few steps in this content for which you must use the command-line interface.
====

* You want to use the _Classic_ System Manager UI for ONTAP 9.7 and earlier releases, not the ONTAP System Manager UI for ONTAP 9.7 and later.
+
https://docs.netapp.com/us-en/ontap/[ONTAP System Manager documentation]

If this content is not suitable for your situation, you should see the following documentation instead:

* https://docs.netapp.com/us-en/ontap/networking/index.html[Network management]
+
Describes how to configure subnets, intercluster LIFs, routes, firewall policies, and other networking components. It also describes how to create an SNMP community for a data storage virtual machine (SVM) and how to manage SNMP traphosts.

* http://www.netapp.com/us/media/tr-4220.pdf[NetApp Technical Report 4220: SNMP Support in Data ONTAP]
+
Describes SNMP support in ONTAP, including a detailed comparison of SNMP support in 7-Mode and ONTAP environments, and a list of all default events that are supported by SNMP traps.
