---
permalink: volume-restore-snapvault/concept_deciding_whether_to_use_the_volume_restore_using_snapvault_express_guide.html
sidebar: sidebar
keywords: 
summary: 'This guide describes how to quickly restore a volume from a SnapVault backup in ONTAP when there is a data loss.'
---
= Deciding whether to use the Volume Restore Using SnapVault Express Guide
:icons: font
:imagesdir: ../media/

[.lead]
This guide describes how to quickly restore a volume from a SnapVault backup in ONTAP when there is a data loss.

You should use this guide if you want to restore from the SnapVault backup in the following way:

* You are working with clusters running ONTAP 9.
* You are a cluster administrator.
* You have configured the SnapVault relationship following the procedure described in the _Volume Backup Using SnapVault Preparation Express Guide_.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-buvault/home.html[Volume express backup using SnapVault]

* You do not want to perform a single file or LUN restore.
* You want to use best practices, not explore every available option.
* You do not want to read a lot of conceptual background.
* You want to use System Manager, not the ONTAP command-line interface or an automated scripting tool.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help/GUID-DF04A607-30B0-4B98-99C8-CB065C64E670.html[Cluster management using System Manager]

* You want to use the _legacy_ OnCommand System Manager UI for ONTAP 9.7 and earlier releases, not the ONTAP System Manager UI for ONTAP 9.7 and later.
+
https://docs.netapp.com/us-en/ontap/[ONTAP System Manager documentation]

If these assumptions are not correct for your situation, or if you want more conceptual background information, you should see the following resources:

* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-dap/home.html[Data protection]
* http://www.netapp.com/us/media/tr-4015.pdf[NetApp Technical Report 4015: SnapMirror Configuration and Best Practices Guide for ONTAP 9.1, 9.2]
* http://www.netapp.com/us/media/tr-4183.pdf[NetApp Technical Report 4183: SnapVault Best Practices Guide]
* http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61550[NetApp Documentation: OnCommand Workflow Automation (current releases)]
+
OnCommand Workflow Automation enables you to run prepackaged workflows that automate management tasks such as the workflows described in Express Guides.
