---
permalink: nfs-config/reference_where_to_find_additional_information.html
sidebar: sidebar
keywords: successful, nfs, test, client, access, configuration, san, protocol, root, volume, express, guide, comprehensive, technical, report, achieve, where to find additional information
summary: "After you have successfully tested NFS client access, you can perform advanced NFS configuration or add SAN access. When protocol access is complete, you should protect the root volume of SVM. There are express guides, comprehensive guides, and technical reports to help you achieve these goals."
---
= Where to find additional information
:icons: font
:imagesdir: ../media/

[.lead]
After you have successfully tested NFS client access, you can perform advanced NFS configuration or add SAN access.When protocol access is complete, you should protect the root volume of SVM. There are express guides, comprehensive guides, and technical reports to help you achieve these goals.

== NFS configuration

You can further configure NFS access using the following comprehensive guides and technical reports:

* https://docs.netapp.com/us-en/ontap/nfs-admin/index.html[NFS management]
+
Describes how to configure and manage file access using the NFS protocol.

* http://www.netapp.com/us/media/tr-4067.pdf[NetApp Technical Report 4067: NFS Best Practice and Implementation Guide]
+
Serves as an NFSv3 and NFSv4 operational guide and provides an overview of ONTAP operating system with a focus on NFSv4.

* https://www.netapp.com/pdf.html?item=/media/16328-tr-4668pdf.pdf[NetApp Technical Report 4668: Name Services Best Practices Guide]
+
Provides a comprehensive list of best practices, limits, recommendations, and considerations when configuring LDAP, NIS, DNS, and local user and group files for authentication purposes.

* https://www.netapp.com/pdf.html?item=/media/19384-tr-4616.pdf[NetApp Technical Report 4616: NFS Kerberos in ONTAP with Microsoft Active Directory]
* https://www.netapp.com/pdf.html?item=/media/19423-tr-4835.pdf[NetApp Technical Report 4835: How to Configure LDAP in ONTAP]
* http://www.netapp.com/us/media/tr-3580.pdf[NetApp Technical Report 3580: NFSv4 Enhancements and Best Practices Guide Data ONTAP Implementation]
+
Describes the best practices that should be followed while implementing NFSv4 components on AIX, Linux, or Solaris clients attached to systems running ONTAP.

== Root volume protection

After configuring protocols on the SVM, you should ensure that its root volume is protected:

* https://docs.netapp.com/us-en/ontap/data-protection/index.html[Data protection]
+
Describes how to create a load-sharing mirror to protect the SVM root volume, which is a NetApp best practice for NAS-enabled SVMs. Also describes how to quickly recover from volume failures or losses by promoting the SVM root volume from a load-sharing mirror
