---
permalink: nfs-config/task_deciding_where_to_provision_the_new_volume.html
sidebar: sidebar
keywords: 
summary: 'Before you create a new NFS volume, you must decide whether to place it in an existing storage virtual machine \(SVM\), and, if so, how much configuration the SVM requires. This decision determines your workflow.'
---
= Deciding where to provision the new volume
:icons: font
:imagesdir: ../media/

[.lead]
Before you create a new NFS volume, you must decide whether to place it in an existing storage virtual machine (SVM), and, if so, how much configuration the SVM requires. This decision determines your workflow.

* If you want to provision a volume on a new SVM, create a new NFS-enabled SVM.
+
link:task_creating_a_protocol_enabled_svm.md#[Creating a new NFS-enabled SVM]
+
You must choose this option if NFS is not enabled on an existing SVM.

* If you want to provision a volume on an existing SVM on which NFS is enabled but not configured, configure NFS access on the existing SVM.
+
xref:task_configuring_access_to_an_existing_svm.adoc[Configuring NFS access on an existing SVM]
+
You should choose this option if you created the SVM for SAN access by using the relevant Express Guide.

* If you want to provision a volume on an existing SVM that is fully configured for NFS access, add an NFS volume to the NFS-enabled SVM.
+
xref:concept_adding_a_protocol_volume_to_a_protocol_enabled_svm.adoc[Adding an NFS volume to an NFS-enabled SVM]
